/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_erdk_ABotanJNI1_NativeCrypto */

#ifndef _Included_com_erdk_ABotanJNI1_NativeCrypto
#define _Included_com_erdk_ABotanJNI1_NativeCrypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_erdk_ABotanJNI1_NativeCrypto
 * Method:    pbkdf2Demo
 * Signature: ([C[BII)Ljava/security/Key;
 */
JNIEXPORT jobject JNICALL Java_com_erdk_ABotanJNI1_NativeCrypto_pbkdf2Demo
  (JNIEnv *, jclass, jcharArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
